spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study
    username: root
    password: '!db1234'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true
